"""
core/generator.py — Calls OpenAI GPT-4o (or returns mock output if MOCK_MODE=true).

Environment variables:
  OPENAI_API_KEY  — required for real mode
  MOCK_MODE       — set to "true" to skip OpenAI and return deterministic test output
  MAX_TOKENS      — max tokens for completion (default: 2000)
"""

import os
import logging
import textwrap

logger = logging.getLogger(__name__)

MOCK_MODE = os.getenv("MOCK_MODE", "false").lower() == "true"
MAX_TOKENS = int(os.getenv("MAX_TOKENS", "2000"))
MODEL = "gpt-4o"


def generate_tests(messages: list[dict]) -> dict:
    """
    Given a messages list (from core/prompt.py), return a dict with:
      - tests: str  — the generated pytest file content
      - tokens_used: int
      - model: str
      - mock_mode: bool
    """
    if MOCK_MODE:
        logger.info("MOCK_MODE=true — returning mock test output")
        return _mock_response(messages)

    return _openai_response(messages)


def _openai_response(messages: list[dict]) -> dict:
    """Calls the real OpenAI API."""
    try:
        from openai import OpenAI  # lazy import so mock mode has zero overhead
    except ImportError:
        raise RuntimeError(
            "openai package not installed. Run: pip install openai"
        )

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "OPENAI_API_KEY environment variable is not set. "
            "Set MOCK_MODE=true to run without an API key."
        )

    client = OpenAI(api_key=api_key)

    response = client.chat.completions.create(
        model=MODEL,
        messages=messages,
        max_tokens=MAX_TOKENS,
        temperature=0.2,
    )

    tests = response.choices[0].message.content.strip()
    # Strip accidental markdown fences if the model added them
    if tests.startswith("```"):
        lines = tests.splitlines()
        tests = "\n".join(
            line for line in lines if not line.strip().startswith("```")
        )

    return {
        "tests": tests,
        "tokens_used": response.usage.total_tokens,
        "model": MODEL,
        "mock_mode": False,
    }


def _mock_response(messages: list[dict]) -> dict:
    """
    Returns a realistic-looking mock Pytest file without calling any API.
    Inspects the user message to tailor the mock slightly.
    """
    user_content = next(
        (m["content"] for m in messages if m["role"] == "user"), ""
    )

    # Try to detect the function/class name from the submitted code snippet
    function_name = "solution"
    for line in user_content.splitlines():
        line = line.strip()
        if line.startswith("def ") and "(" in line:
            function_name = line.split("def ")[1].split("(")[0].strip()
            break
        if line.startswith("class ") and ":" in line:
            function_name = line.split("class ")[1].split("(")[0].split(":")[0].strip()
            break

    mock_tests = textwrap.dedent(f"""\
        \"\"\"
        Auto-generated Pytest suite for `{function_name}`.
        Generated by TestForge Cloud (mock mode — no API key required).
        \"\"\"

        import pytest
        from solution import {function_name}


        # ---------------------------------------------------------------------------
        # Happy path
        # ---------------------------------------------------------------------------

        def test_{function_name}_basic():
            \"\"\"Verifies the function returns the expected result for typical input.\"\"\"
            result = {function_name}(2, 3)
            assert result is not None


        def test_{function_name}_returns_correct_type():
            \"\"\"Verifies the return type is as expected.\"\"\"
            result = {function_name}(1, 1)
            assert isinstance(result, (int, float, str, list, dict, bool))


        # ---------------------------------------------------------------------------
        # Edge cases
        # ---------------------------------------------------------------------------

        def test_{function_name}_with_zero():
            \"\"\"Verifies the function handles zero inputs without crashing.\"\"\"
            result = {function_name}(0, 0)
            assert result is not None


        def test_{function_name}_with_negative():
            \"\"\"Verifies the function handles negative numbers correctly.\"\"\"
            result = {function_name}(-1, -1)
            assert result is not None


        def test_{function_name}_large_values():
            \"\"\"Verifies the function handles large numeric inputs.\"\"\"
            result = {function_name}(10_000, 10_000)
            assert result is not None


        # ---------------------------------------------------------------------------
        # Parametrized suite
        # ---------------------------------------------------------------------------

        @pytest.mark.parametrize("a, b", [
            (0, 1),
            (1, 0),
            (-1, 1),
            (100, 200),
            (999, -999),
        ])
        def test_{function_name}_parametrized(a, b):
            \"\"\"Runs the function across a range of input pairs.\"\"\"
            result = {function_name}(a, b)
            assert result is not None


        # ---------------------------------------------------------------------------
        # Error handling
        # ---------------------------------------------------------------------------

        def test_{function_name}_type_error():
            \"\"\"Verifies the function raises TypeError on invalid input types.\"\"\"
            with pytest.raises((TypeError, ValueError)):
                {function_name}("not_a_number", None)
    """)

    return {
        "tests": mock_tests,
        "tokens_used": 0,
        "model": "mock",
        "mock_mode": True,
    }
